version: '3.4'

services:
  gringottsbank.api:
    image: ${DOCKER_REGISTRY-}gringottsbankapi
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      DATABASE_SSL: "false"
      DATABASE_URL: "postgres://postgres:root@db:5432/GringottsBank"
      JWT_SECRET: "SHpcEhq9cLRwC93tmjM7GxpZ6Rr7us5n"
    depends_on:
      - db
    networks:
      - gringottsbank
  db:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    networks:
      - gringottsbank
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - gringottsbankdata:/var/lib/postgresql/data
networks:
  gringottsbank:
    driver: bridge
volumes:
  gringottsbankdata: