name: Deploy to Heroku

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/readme.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/web
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image and deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:login
          docker build --file prod.Dockerfile --tag ${{ env.HEROKU_REGISTRY_IMAGE }}:latest .
          docker push ${{ env.HEROKU_REGISTRY_IMAGE }}:latest
          heroku container:release -a ${{ env.HEROKU_APP_NAME }} web
